[tool.poetry]
name = "fm"
version = "0.1.0"
description = "Frappe Manager for Local Development Setup"
authors = ["Xieyt <alokmilenium@gmail.com>"]
readme = "README.md"
packages = [{include = "fm"}]
include = ["fm/templates/*"]

[tool.poetry.scripts]
fm = "fm.cli:run"

[tool.poetry.dependencies]
python = "^3.11"
jinja2 = "^3.1.2"
fire = "^0.5.0"
rich = "^13.4.2"
python-on-whales = "^0.63.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
