[tool.poetry]
name = "fm"
version = "0.3.0"
description = "Frappe Manager for Local Development Setup"
authors = ["Xieyt <alokmilenium@gmail.com>"]
readme = "README.md"
include = ["fm/templates/*"]
#packages = [{include = "fm"}]

[tool.poetry.scripts]
fm = "fm.main:app"

[tool.poetry.dependencies]
python = "^3.11"
jinja2 = "^3.1.2"
python-on-whales = "^0.63.0"
typer = {extras = ["all"], version = "^0.9.0"}
pyyaml = "^6.0.1"
psutil = "^5.9.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
