[tool.poetry]
name = "fm"
version = "0.8.0"
description = "Frappe Manager for local frappe development environment management."
authors = ["Xieyt <alokmilenium@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
fm = "fm.main:app"

[tool.poetry.dependencies]
python = "^3.11"
jinja2 = "^3.1.2"
typer = {extras = ["all"], version = "^0.9.0"}
pyyaml = "^6.0.1"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
